server:
  port: 8882
spring:
  application:
    #和git里的文件名（application）对应
    name: dymw-config-client
eureka:
  instance:
    #以IP地址注册到服务中心，相互注册使用IP地址
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
dymw: zgf123

