
server:
  port: 8002
spring:
  application:
    name: summer-cloud-config-client
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   ## 注册中心eurka地址
    
   

neo:
  hello: hello im dev update2  github  123456789101122334455667788991011
    